DROP DATABASE IF EXISTS `db`;
CREATE DATABASE `db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP DATABASE IF EXISTS `db_0`;
CREATE DATABASE `db_0` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP DATABASE IF EXISTS `db_1`;
CREATE DATABASE `db_1` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP DATABASE IF EXISTS `db_2`;
CREATE DATABASE `db_2` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP DATABASE IF EXISTS `db_3`;
CREATE DATABASE `db_3` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP DATABASE IF EXISTS `db_4`;
CREATE DATABASE `db_4` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP DATABASE IF EXISTS `db_5`;
CREATE DATABASE `db_5` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP DATABASE IF EXISTS `db_6`;
CREATE DATABASE `db_6` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP DATABASE IF EXISTS `db_7`;
CREATE DATABASE `db_7` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP DATABASE IF EXISTS `db_8`;
CREATE DATABASE `db_8` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP DATABASE IF EXISTS `db_9`;
CREATE DATABASE `db_9` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP DATABASE IF EXISTS `db_10`;
CREATE DATABASE `db_10` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP DATABASE IF EXISTS `db_11`;
CREATE DATABASE `db_11` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP DATABASE IF EXISTS `db_12`;
CREATE DATABASE `db_12` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP DATABASE IF EXISTS `db_13`;
CREATE DATABASE `db_13` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP DATABASE IF EXISTS `db_14`;
CREATE DATABASE `db_14` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

DROP DATABASE IF EXISTS `db_15`;
CREATE DATABASE `db_15` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;